# Generated by Django 4.2.5 on 2023-09-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='images/')),
                ('Content', models.CharField(max_length=1000)),
            ],
        ),
    ]
