# Generated by Django 4.2.5 on 2023-09-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_blogs_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blogs',
            new_name='blogss',
        ),
    ]
